npmRegistryServer: "https://registry.npmjs.org"
defaultSemverRangePrefix: ""
nodeLinker: node-modules
enableImmutableInstalls: false

npmScopes:
  ids-ts:
    npmRegistryServer: "https://registry.npmjs.intuit.com"
  design-systems:
    npmRegistryServer: "https://registry.npmjs.intuit.com"
  sbg:
    npmRegistryServer: "https://registry.npmjs.intuit.com"
  genux-ds:
    npmRegistryServer: "https://registry.npmjs.intuit.com"
  cgds:
    npmRegistryServer: "https://registry.npmjs.intuit.com"
  design-tokens:
    npmRegistryServer: "https://registry.npmjs.intuit.com"
  appfabric:
    npmRegistryServer: "https://registry.npmjs.intuit.com"
  qbds:
    npmRegistryServer: "https://registry.npmjs.intuit.com"
