// App.tsx — AppShell version with FusionShell layout. Generated by scaffold-appshell.
import { useEffect } from 'react'
import { HashRouter, Routes, Route, Outlet, Navigate, useNavigate, useLocation } from 'react-router-dom'
import ErrorBoundary from './ErrorBoundary'
import { FusionProvider } from './contexts/fusion'
import FusionShell from './components/FusionShell'
import { FUSION_CONFIG } from './navigation'
import { repairIncomingRoute, resolveCatchAllRoute } from './lib/prototypeRoutes'
import DataReviewPage from './pages/DataReviewPage'
import SmartReturnPage from './pages/SmartReturnPage'
import ImportConfirmationPage from './pages/ImportConfirmationPage'
import CheckReturnPage from './pages/CheckReturnPage'
import ReturnInsightsPage from './pages/ReturnInsightsPage'
import WorkspacePage from './pages/WorkspacePage'
import HomePage from './pages/HomePage'
import NotFoundPage from './pages/NotFoundPage'

// HashRouter paths live in the URL fragment (#/…), not under the static asset base
// (e.g. /SmartReview-AIc2/). Using BASE_URL here breaks GitHub Pages — routes like
// #/data-review never match when basename is the repo subpath.
const ROUTER_BASENAME = '/'


/** Fix path-only GitHub Pages URLs and encoded hash links before routing. */
function HashRouteNormalizer() {
  const navigate = useNavigate()
  useEffect(() => {
    const repaired = repairIncomingRoute()
    if (repaired) navigate(repaired, { replace: true })
  }, [navigate])
  return null
}

/** Unknown hash routes → SmartReturn or reviewer data-review based on role. */
function CatchAllRedirect() {
  const location = useLocation()
  return <Navigate to={resolveCatchAllRoute(location.search)} replace />
}

function AppLayout() {
  return (
    <FusionShell businessName={FUSION_CONFIG.businessName}>
      <Outlet />
    </FusionShell>
  )
}

// APP_PAGES — add new app page routes here (managed by /page skill)
const APP_PAGES: { path: string; component: React.ComponentType }[] = []

export default function App() {
  return (
    <ErrorBoundary>
      <HashRouter basename={ROUTER_BASENAME}>
        <FusionProvider pathPrefix={FUSION_CONFIG.pathPrefix || ''}>
          <HashRouteNormalizer />
          <Routes>
            {/* SmartReview prototype — outside the QBO Fusion shell */}
            <Route path="/" element={<Navigate to="/smart-return" replace />} />
            <Route path="/import-hub" element={<Navigate to="/smart-return" replace />} />
            <Route path="/smart-return" element={<SmartReturnPage />} />
            <Route path="/import-confirmation" element={<ImportConfirmationPage />} />
            <Route path="/data-review" element={<DataReviewPage />} />
            <Route path="/check-return" element={<CheckReturnPage />} />
            <Route path="/check-return/insights" element={<ReturnInsightsPage />} />

            <Route element={<AppLayout />}>
              <Route path="/home" element={<HomePage />} />
              <Route path="/workspace" element={<WorkspacePage />} />
              {APP_PAGES.map(({ path, component: Page }) => (
                <Route key={path} path={`/app/${path}`} element={<Page />} />
              ))}
              <Route path="/app/*" element={<NotFoundPage />} />
            </Route>

            {/* Unknown paths → role-aware landing */}
            <Route path="*" element={<CatchAllRedirect />} />
          </Routes>
        </FusionProvider>
      </HashRouter>
    </ErrorBoundary>
  )
}
