// App.tsx — AppShell version with FusionShell layout. Generated by scaffold-appshell.
import { HashRouter, Routes, Route, Outlet, Navigate } from 'react-router-dom'
import ErrorBoundary from './ErrorBoundary'
import { FusionProvider } from './contexts/fusion'
import FusionShell from './components/FusionShell'
import { FUSION_CONFIG } from './navigation'
import OnboardingPage from './pages/OnboardingPage'
import WorkspacePage from './pages/WorkspacePage'
import HomePage from './pages/HomePage'
import NotFoundPage from './pages/NotFoundPage'

function AppLayout() {
  return (
    <FusionShell businessName={FUSION_CONFIG.businessName}>
      <Outlet />
    </FusionShell>
  )
}

// APP_PAGES — add new app page routes here (managed by /page skill)
const APP_PAGES: { path: string; component: React.ComponentType }[] = [
  // Example: { path: 'accounting/bank-transactions', component: BankTransactionsPage },
]

export default function App() {
  return (
    <ErrorBoundary>
      <HashRouter>
        <FusionProvider pathPrefix={FUSION_CONFIG.pathPrefix || ''}>
          <Routes>
            <Route path="/onboarding" element={<OnboardingPage />} />
            <Route element={<AppLayout />}>
              <Route path="/" element={<Navigate to="/home" replace />} />
              <Route path="/home" element={<HomePage />} />
              <Route path="/workspace" element={<WorkspacePage />} />
              {APP_PAGES.map(({ path, component: Page }) => (
                <Route key={path} path={`/app/${path}`} element={<Page />} />
              ))}
              <Route path="/app/*" element={<NotFoundPage />} />
              <Route path="*" element={<NotFoundPage />} />
            </Route>
          </Routes>
        </FusionProvider>
      </HashRouter>
    </ErrorBoundary>
  )
}
